#pragma once

using namespace ATL;

template <class T>
class CProxy_ITestObjEvents : public IConnectionPointImpl<T, &__uuidof( _ITestObjEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
